version: '3'
services:
  webserver:
    container_name: webserver
    build: ./php
    ports:
      - "80:80"
      - "443:443"
    restart: 'unless-stopped'
    volumes:
      - /var/www/:/var/www/html/
    links:
      - mysql_server
      - redis_server
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "500k"

  redis_server:
    container_name: redish_cache
    build: ./redish
    ports: 
      - "6379:6379"
    restart: 'unless-stopped'
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "500k"
   
  mysql_server:
    container_name: mysql_server
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    build: ./mysql
    restart: 'unless-stopped'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_USER: standardUser
      MYSQL_PASSWORD: standardUser
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "500k"

volumes:
  mariadb-volume:
